name: Build & Deploy to Netlify

on:
  workflow_run:
    workflows: ["Run Tests and Coverage"]
    types:
      - completed
    branches:
      - main

jobs:
  build-deploy:
    environment: recette
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: front
        run: yarn

      - name: Build Quasar App
        working-directory: front
        run: |
          yarn global add @quasar/cli
          quasar build
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          FRONT_URL: ${{ vars.FRONT_URL }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID_1 }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=front/dist/spa
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID_1 }}
