name: Deploy Back to Railway

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Run Tests and Coverage"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: recette
    if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' }}
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: ${{ vars.RAILWAY_SERVICE_ID_1 }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Railway
        working-directory: back
        run: railway up --service=$SVC_ID